on:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

permissions:
  contents: read

env:
  TAG: ${{ github.ref_name }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write  # for OIDC publishing

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3.1.4

      - name: Confirm tag name matches pyproject.toml
        run: |
          VERSION=$(grep "version = .*" pyproject.toml | sed -E 's/.*"(.*)"/\1/')
          [ "v$VERSION" = "$TAG" ] || exit 1

      - name: Build package
        run: |
          pip install -r .github/workflows/requirements/build.txt --require-hashes
          python -m build

      - name: Publish to PyPiTest
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8 # v1.8.8
        with:
          repository-url: https://test.pypi.org/legacy/